### PR TITLE
Add include/exclude options to whitelist/blacklist top-level property keys

### PR DESCRIPTION
**Pull request by jamesdahlfred**

### CODE REVIEW

**Comment by jcbvm** [comment]
Thanks for contributing :)

**Comment by jamesdahlfred** [comment]
Mostly scratching my own itch. In the future, I'd like to improve the string matching to regex matching, as well as the option to filter an arbitrary number of levels (not just top-level), but the functionality suits my needs for now. Thanks for making this in the first place!

**Comment by jcbvm** [comment]
I also made this for my own needs, but thought it would be useful for others. I was also thinking of adding regex support and nested includes/excludes support when I saw your PR, would be nice to add later on indeed.

**Comment by jcbvm** [comment]
I added regex and deep lookup support to includes/excludes in v0.5.0.

**Pull request merged**
